# Project
maven_group                 = me.itzme1on
release_channel             = beta

# Minecraft / Forge
minecraft_version           = 1.20.1
minecraft_min_version       = 1.20
minecraft_max_version       = 1.20.2
forge_version               = 47.3.12
forge_version_range         = [46,)
forge_loader_version_range  = [46,)
parchment_version           = 2023.09.03

# Dependencies
architectury_api_version    = 9.2.14

# Mod options
mod_version                 = 1.0.0-beta
mod_id                      = alcocraftpluscreate
mod_display_name            = Create: AlcoCraft+
mod_authors                 = itzme1on
mod_description             = Create integration for AlcoCraft+: automate brewing with belts, pipes and the spout.
mod_license                 = MIT
mod_git_url                 = https://github.com/itzme1on/AlcoCraft-Plus-Create-Addon
mod_issues_url              = https://github.com/itzme1on/AlcoCraft-Plus-Create-Addon/issues
mod_modrinth_id             = yMRHYzX9
mod_curseforge_id           = 1576025

# Loom
loom.platform               = forge

# Gradle
org.gradle.jvmargs          = -Xmx2G
org.gradle.parallel         = true
